Added option to build screen but not switch to it. Updated read me
kulothunganug/kivy-lazy-loading-template pull request #4
Opened 2023-01-10 14:29 UTC by LazzaAU

For an existing app, there may be occasions like i had where you want to build a screen but not switch to that screen. I've added a simple arg to prevent the screen switching in these occasions. Also handy to use when you want to load a screen in the back ground but not switch to it.

Added two things i noticed during configuration that i thought should go in the readme. feel free to revert :)

Otherwise. thanks for the code. It worked great and my app is super speedy now :)

2023-01-12 14:54 UTC, Kulothungan16 requested changes
The information about buildozer stuff is crucial, thanks for filling it up!

2023-01-12 14:54 UTC, Kulothungan16 commented on README.md
> +* Don't change self.root = Root() for self.another_name = Root(), It won't work if it's not called root
We already have lot of points in the README, specifying this info [here](https://github.com/Kulothungan16/kivy-lazy-loading-template/blob/68b772d91c4fca8042ed9bec4bf41f0290ec2f5d/main.py#L17) maybe with some [links](https://kivy.org/doc/stable/api-kivy.app.html#kivy.app.App.root) would be great

2023-01-12 14:54 UTC, kulothunganug commented on libs/uix/root.py
> +    def set_current(self, screen_name, side="left", _from_goback=False, change_screens=True):
I think we don't need this functionality because if they don't want to switch to a screen, they can just comment it out or also can implement your technique (as they have the freedom do modify)

2023-01-13 05:56 UTC, LazzaAU commented on libs/uix/root.py
> +    def set_current(self, screen_name, side="left", _from_goback=False, change_screens=True):
No worries :) done.

2023-01-13 16:08 UTC, Kulothungan16 approved these changes

2023-01-13 16:09 UTC, merged

2023-01-13 16:10 UTC, Kulothungan16 commented
Thanks for the contribution!